### ISSUE TITLE
atmosphere-gwt20-client-2.4.3 fails to build with GWT 2.7.0

### ISSUE THREAD

**Issue by robert7k** [Atmosphere/atmosphere-extensions#233]
Building a GWT-2.7.0 project with atmosphere-gwt20-client-2.4.3 leads to the following error while compiling the GWT code:

```
Caused by: java.lang.NoSuchMethodError: com.google.gwt.user.rebind.rpc.SerializableTypeOracleBuilder.<init>(Lcom/google/gwt/core/ext/TreeLogger;Lcom/google/gwt/core/ext/PropertyOracle;Lcom/google/gwt/core/ext/GeneratorContext;)V
     [java]     at org.atmosphere.gwt20.rebind.SerializerGenerator.generateIncrementally(SerializerGenerator.java:87)
     [java]     at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:754)
     [java]     at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
     [java]     at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
     [java]     at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
     [java]     at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:485)
     [java]     at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:443)
     [java]     at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:576)
     [java]     at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:306)
     [java]     at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
     [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
     [java]     at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
     [java]     ... 40 more
     [java]       [ERROR] at FilePresenter.java(137): GWT.create(RPCSerializer.class)
     [java]          com.google.gwt.dev.jjs.ast.JMethodCall
     [java]       [ERROR] at FilePresenter.java(137): (RPCSerializer) GWT.create(RPCSerializer.class)
     [java]          com.google.gwt.dev.jjs.ast.JCastOperation
     [java]       [ERROR] at FilePresenter.java(137): RPCSerializer rpc_serializer = (RPCSerializer) GWT.create(RPCSerializer.class)
     [java]          com.google.gwt.dev.jjs.ast.JDeclarationStatement
     [java]       [ERROR] at FilePresenter.java(122): {
```

This seems to be a regression as the same code compiles fine when using atmosphere-gwt20-client-2.4.0
[
Other people seem to have the same problem](http://stackoverflow.com/questions/36354043/unable-to-compile-atmosphere-gwt-client-side).

**Comment by olivergg** [comment]
See https://github.com/Atmosphere/atmosphere-extensions/issues/227
