### ISSUE TITLE
GWT 2.7 super dev mode

### ISSUE THREAD

**Issue by zsenyeg** [Atmosphere/atmosphere-extensions#194]
Hey Guys,

I'm using Atmosphere GWT extension branch 2.2.2-GWT27 and i have a little problem when i use this code piece:

AutoBeanClientSerializer json_serializer = new AutoBeanClientSerializer();
json_serializer.registerBeanFactory(beanFactory, ITest.class);

Super dev mode compilation error is:

[ERROR] Errors in 'org/atmosphere/gwt20/client/AutoBeanClientSerializer.java'
[ERROR] Line 85: Only class literals may be used as arguments to GWT.create()

If i remove the problematic lines from my code, and i left only the package import of AutoBeanClientSerializer class, the gwt compiler still produce the same error. I've checked the jar file, and i've found that the jar file containing both source and class files. Is it possible that the gwt compiler trying to recompile java sources from dependent jar files?

My project - and this problematic code piece - has worked without any problem with gwt 2.6.1 and atmosphere GWT extension 2.2.0 using not super development mode.

I've found a similar issue in closed state, but i'm nearly sure my interfaces are valid.
https://github.com/Atmosphere/atmosphere-extensions/issues/169

I've found a pull request with a possible fix by removing the problematic method from AutoBeanClientSerializer class.
https://github.com/Atmosphere/atmosphere-extensions/pull/171

Sorry for my english, i'm not a native.

Could you help me pls?

Cheers

**Comment by jfarcand** [comment]
If you apply #171, does it help? Try it and let me know...I'm swamped this week but will do my best to help.

**Comment by zsenyeg** [comment]
Yes, if i apply #171 there's no compilation error.

**Comment by jfarcand** [comment]
Nomn in 2.4.0 by default

**Comment by confile** [comment]
This problem still exist in: 

```
  compile 'org.atmosphere.extensions:atmosphere-gwt20-client:2.4.1'
  compile 'org.atmosphere.extensions:atmosphere-gwt20-common:2.4.1'
```

**Comment by confile** [comment]
@zsenyeg pull request #171 also works with GWT 2.8 https://github.com/Atmosphere/atmosphere-extensions/issues/216
